[project]
name = "jamiat-mcp-server"
version = "0.1.0"
description = "A simple MCP server for managing Jamiat's IT projects."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.128.3",
    "mcp>=1.26.0",
]
